[2024-02-23 12:06:15,878 submission_checker.py:3220 ERROR] closed/HPE/results/HPE_ProLiant_DL380a_L40S_PCIe_48GBx4_TRT, field host_network_card_count is missing
[2024-02-23 12:06:15,878 submission_checker.py:3240 WARNING] closed/HPE/results/HPE_ProLiant_DL380a_L40S_PCIe_48GBx4_TRT, field host_networking_card_count is unknown
[2024-02-23 12:06:15,878 submission_checker.py:3662 INFO] ---
[2024-02-23 12:06:15,878 submission_checker.py:3668 INFO] ---
[2024-02-23 12:06:15,878 submission_checker.py:3671 ERROR] NoResults closed/HPE/results/HPE_ProLiant_DL380a_L40S_PCIe_48GBx4_TRT
[2024-02-23 12:06:15,878 submission_checker.py:3753 INFO] ---
[2024-02-23 12:06:15,878 submission_checker.py:3754 INFO] Results=0, NoResults=1, Power Results=0
[2024-02-23 12:06:15,878 submission_checker.py:3761 INFO] ---
[2024-02-23 12:06:15,878 submission_checker.py:3762 INFO] Closed Results=0, Closed Power Results=0

[2024-02-23 12:06:15,878 submission_checker.py:3767 INFO] Open Results=0, Open Power Results=0

[2024-02-23 12:06:15,878 submission_checker.py:3772 INFO] Network Results=0, Network Power Results=0

[2024-02-23 12:06:15,878 submission_checker.py:3777 INFO] ---
[2024-02-23 12:06:15,878 submission_checker.py:3779 INFO] Systems=0, Power Systems=0
[2024-02-23 12:06:15,878 submission_checker.py:3780 INFO] Closed Systems=0, Closed Power Systems=0
[2024-02-23 12:06:15,878 submission_checker.py:3785 INFO] Open Systems=0, Open Power Systems=0
[2024-02-23 12:06:15,878 submission_checker.py:3790 INFO] Network Systems=0, Network Power Systems=0
[2024-02-23 12:06:15,878 submission_checker.py:3795 INFO] ---
[2024-02-23 12:06:15,878 submission_checker.py:3797 ERROR] SUMMARY: submission has errors
